"""
Lightweight data contracts for every input the dashboard displays.

WHAT IT DOES:
    Declares the required columns per artefact (matched to the ACTUAL pipeline
    schemas, not the prototype's) and provides validators that return
    stakeholder-readable problem strings. The critical control lives in
    check_queue_is_official(): the review queue must carry the CLEAN panel's
    values — a queue row whose trade value/quantity matched a scenario-injected
    copy instead of the official panel would be a synthetic leak.

Note: an obs_id appearing in both the queue and the scenario-injection list is
legitimate (injections transform a COPY of the panel), so the check compares
VALUES, never just identifiers.
"""

from __future__ import annotations

import math

import pandas as pd

# Required columns per artefact — verified against the files generated by
# src/03..07. Extra columns are always allowed; missing ones are contract errors.
QUEUE_REQUIRED_COLUMNS = {
    "rank", "obs_id", "year", "exporter_iso3", "importer_iso3", "hs6",
    "family_id", "product_name", "trade_value_usd", "quantity_metric_ton",
    "unit_value_usd_per_metric_ton", "benchmark_price_usd_per_metric_ton",
    "selected_review_priority_score", "rule_score", "selected_challenger_score",
    "quality_status", "data_quality_score", "valid_extreme_flag",
    "key_evidence_count",
}
EVIDENCE_REQUIRED_COLUMNS = {
    "evidence_id", "obs_id", "evidence_type", "metric_name", "observed_value",
    "comparison_value", "comparison_group", "threshold", "severity",
    "plain_english_summary", "caveat",
}
PANEL_REQUIRED_COLUMNS = {
    "obs_id", "year", "exporter_iso3", "importer_iso3", "corridor_id", "hs6",
    "family_id", "product_name", "trade_value_usd", "quantity_metric_ton",
    "unit_value_usd_per_metric_ton", "benchmark_price_usd_per_metric_ton",
    "benchmark_residual", "quality_status", "data_quality_score", "model_eligible",
}
FEATURES_REQUIRED_COLUMNS = {
    "obs_id", "year", "exporter_iso3", "importer_iso3", "hs6", "family_id",
    "exporter_name", "importer_name", "robust_historical_z", "benchmark_residual",
    "benchmark_adjusted_drift", "same_family_year_peer_percentile",
    "unit_value_yoy_change", "trade_value_yoy_change", "quantity_yoy_change",
    "value_quantity_divergence", "corridor_novelty_flag",
    "corridor_reactivation_flag", "data_quality_flags", "benchmark_caveat",
}
MODEL_COMPARISON_REQUIRED_COLUMNS = {
    "split", "family_id", "model", "n", "positives", "k", "precision_at_k",
    "recall_at_k", "lift_at_k", "average_precision",
    "hard_negative_false_positive_rate", "ordinary_false_positive_rate",
}
# Exact model/split names written by src/06 — anything else is a schema drift.
EXPECTED_MODELS = {"rule", "logistic", "xgboost", "isolation", "hybrid"}
EXPECTED_SPLITS = {"validation", "test"}

# Label/scenario columns that must NEVER appear in official-facing tables.
FORBIDDEN_OFFICIAL_COLUMNS = {
    "scenario_id", "synthetic_review_priority", "hard_negative", "seed", "split",
}

PLAUSIBLE_YEARS = range(2000, 2101)


def _missing(frame: pd.DataFrame, required: set[str]) -> list[str]:
    missing = sorted(required - set(frame.columns))
    return [f"missing required columns: {missing}"] if missing else []


def _check_hs6(frame: pd.DataFrame) -> list[str]:
    # HS6 must be a six-character string for every row (leading zeros intact).
    if "hs6" not in frame.columns:
        return []
    bad = frame["hs6"].astype("string").str.fullmatch(r"\d{6}")
    if not bool(bad.all()):
        examples = frame.loc[~bad.fillna(False), "hs6"].head(3).tolist()
        return [f"hs6 values are not six-character digit strings, e.g. {examples}"]
    return []


def _check_years(frame: pd.DataFrame) -> list[str]:
    if "year" not in frame.columns:
        return []
    years = pd.to_numeric(frame["year"], errors="coerce")
    if years.isna().any() or not years.dropna().astype(int).isin(PLAUSIBLE_YEARS).all():
        return ["year column contains implausible or non-numeric values"]
    return []


def validate_queue(queue: pd.DataFrame) -> list[str]:
    problems = _missing(queue, QUEUE_REQUIRED_COLUMNS)
    if problems:
        return problems
    if queue.empty:
        problems.append("review queue is empty")
    if not queue["obs_id"].is_unique:
        problems.append("obs_id is not unique in the review queue")
    problems += _check_hs6(queue)
    problems += _check_years(queue)
    scores = pd.to_numeric(queue["selected_review_priority_score"], errors="coerce")
    if scores.isna().any() or (scores < 0).any() or (scores > 1).any():
        problems.append("selected_review_priority_score is not numeric in [0, 1]")
    leaked = sorted(FORBIDDEN_OFFICIAL_COLUMNS & set(queue.columns))
    if leaked:
        problems.append(f"official queue exposes scenario/label columns: {leaked}")
    return problems


def validate_evidence(evidence: pd.DataFrame, queue: pd.DataFrame | None = None) -> list[str]:
    problems = _missing(evidence, EVIDENCE_REQUIRED_COLUMNS)
    if problems:
        return problems
    if evidence.empty:
        problems.append("evidence table is empty")
    if not evidence["evidence_id"].is_unique:
        problems.append("evidence_id is not unique")
    if pd.to_numeric(evidence["observed_value"], errors="coerce").isna().any():
        problems.append("observed_value contains non-numeric entries")
    if queue is not None and "obs_id" in queue.columns:
        orphans = ~evidence["obs_id"].isin(set(queue["obs_id"]))
        if bool(orphans.any()):
            problems.append(
                f"{int(orphans.sum())} evidence rows do not join to a review-queue obs_id"
            )
    return problems


def validate_panel(panel: pd.DataFrame) -> list[str]:
    problems = _missing(panel, PANEL_REQUIRED_COLUMNS)
    if problems:
        return problems
    if panel.empty:
        problems.append("panel is empty")
    if not panel["obs_id"].is_unique:
        problems.append("obs_id is not unique in the panel")
    problems += _check_hs6(panel)
    problems += _check_years(panel)
    return problems


def validate_features(features: pd.DataFrame) -> list[str]:
    problems = _missing(features, FEATURES_REQUIRED_COLUMNS)
    if problems:
        return problems
    if not features["obs_id"].is_unique:
        problems.append("obs_id is not unique in the feature table")
    problems += _check_hs6(features)
    return problems


def validate_model_comparison(comparison: pd.DataFrame) -> list[str]:
    problems = _missing(comparison, MODEL_COMPARISON_REQUIRED_COLUMNS)
    if problems:
        return problems
    unknown_models = sorted(set(comparison["model"]) - EXPECTED_MODELS)
    if unknown_models:
        problems.append(f"unexpected model names: {unknown_models}")
    unknown_splits = sorted(set(comparison["split"]) - EXPECTED_SPLITS)
    if unknown_splits:
        problems.append(f"unexpected split names: {unknown_splits}")
    return problems


def check_queue_is_official(queue: pd.DataFrame, panel: pd.DataFrame) -> list[str]:
    # THE synthetic-leak control: every queue row must exist in the clean panel
    # AND carry the clean panel's trade value/quantity (scenario injections
    # changed those values in a copy — matching values proves official data).
    problems: list[str] = []
    merged = queue.merge(
        panel[["obs_id", "trade_value_usd", "quantity_metric_ton"]],
        on="obs_id", how="left", suffixes=("", "_panel"),
    )
    unmatched = merged["trade_value_usd_panel"].isna()
    if bool(unmatched.any()):
        problems.append(
            f"{int(unmatched.sum())} queue rows have obs_ids absent from the clean panel"
        )
    for queue_col, panel_col in [
        ("trade_value_usd", "trade_value_usd_panel"),
        ("quantity_metric_ton", "quantity_metric_ton_panel"),
    ]:
        both = merged[[queue_col, panel_col]].dropna()
        drift = ~both.apply(
            lambda r: math.isclose(r.iloc[0], r.iloc[1], rel_tol=1e-9, abs_tol=1e-9), axis=1
        )
        if bool(drift.any()):
            problems.append(
                f"{int(drift.sum())} queue rows disagree with the clean panel on "
                f"{queue_col} — possible scenario-injected values"
            )
    return problems


def run_integrity_report(
    queue: pd.DataFrame,
    evidence: pd.DataFrame,
    panel: pd.DataFrame,
    features: pd.DataFrame,
    comparison: pd.DataFrame,
) -> dict[str, list[str]]:
    # One dict per contract; empty lists mean pass. Rendered on Model Evaluation & Controls
    # and asserted by the test suite.
    return {
        "review_queue": validate_queue(queue),
        "evidence": validate_evidence(evidence, queue),
        "panel": validate_panel(panel),
        "features": validate_features(features),
        "model_comparison": validate_model_comparison(comparison),
        "queue_is_official": check_queue_is_official(queue, panel),
    }
